/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//GAGAS CAHYA KAMAJENGAN_3F_2310631170018_TUGAS PERTEMUAN 10

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class IdentitasMahasiswa extends javax.swing.JFrame {
    private DefaultTableModel model;

    /**
     * Creates new form IdentitasMahasiswa
     */
    public IdentitasMahasiswa() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        NPM = new javax.swing.JPanel();
        npm = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Matakuliah = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        nilai1 = new javax.swing.JLabel();
        nilai2 = new javax.swing.JLabel();
        nilai3 = new javax.swing.JLabel();
        nilai4 = new javax.swing.JLabel();
        nilai5 = new javax.swing.JLabel();
        nilaiAkhir = new javax.swing.JLabel();
        simpanData = new javax.swing.JButton();
        hapusData = new javax.swing.JButton();
        ketNPM = new javax.swing.JTextField();
        ketNama = new javax.swing.JTextField();
        ketAlamat = new javax.swing.JTextField();
        ketMatakuliah = new javax.swing.JTextField();
        ketNilai1 = new javax.swing.JTextField();
        ketNilai2 = new javax.swing.JTextField();
        ketNilai3 = new javax.swing.JTextField();
        ketNilai4 = new javax.swing.JTextField();
        ketNilai5 = new javax.swing.JTextField();
        ketNilaiAkhir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NPM.setBackground(new java.awt.Color(204, 204, 204));

        npm.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        npm.setText("NPM");

        Nama.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        Nama.setText("Nama");

        Matakuliah.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        Matakuliah.setText("Mata Kuliah");

        Alamat.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        Alamat.setText("Alamat");

        nilai1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nilai1.setText("Nilai 1 (10%)");

        nilai2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nilai2.setText("Nilai 2 (15%)");

        nilai3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nilai3.setText("Nilai 3 - UTS (25%)");

        nilai4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nilai4.setText("Nilai 4 (15%)");

        nilai5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nilai5.setText("Nilai 5 (35%)");

        nilaiAkhir.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        nilaiAkhir.setText("Nilai Akhir");

        simpanData.setText("Simpan");
        simpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanDataActionPerformed(evt);
            }
        });

        hapusData.setText("Hapus");
        hapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDataActionPerformed(evt);
            }
        });

        ketNPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketNPMActionPerformed(evt);
            }
        });

        ketNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketNamaActionPerformed(evt);
            }
        });

        ketAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketAlamatActionPerformed(evt);
            }
        });

        ketMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketMatakuliahActionPerformed(evt);
            }
        });

        ketNilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketNilai1ActionPerformed(evt);
            }
        });

        ketNilai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketNilai2ActionPerformed(evt);
            }
        });

        ketNilai3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketNilai3ActionPerformed(evt);
            }
        });

        ketNilai4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketNilai4ActionPerformed(evt);
            }
        });

        ketNilai5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketNilai5ActionPerformed(evt);
            }
        });

        ketNilaiAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketNilaiAkhirActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(51, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NPM", "Nama", "Alamat", "Mata Kuliah", "Nilai Akhir"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout NPMLayout = new javax.swing.GroupLayout(NPM);
        NPM.setLayout(NPMLayout);
        NPMLayout.setHorizontalGroup(
            NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NPMLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPMLayout.createSequentialGroup()
                        .addComponent(npm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ketNPM, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NPMLayout.createSequentialGroup()
                        .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nama)
                            .addComponent(Alamat)
                            .addComponent(Matakuliah)
                            .addGroup(NPMLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(simpanData)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hapusData)
                            .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ketNama, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(ketAlamat)
                                .addComponent(ketMatakuliah)))))
                .addGap(71, 71, 71)
                .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nilaiAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nilai4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nilai3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nilai2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nilai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nilai5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ketNilai1)
                    .addComponent(ketNilai2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(ketNilai3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(ketNilai4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(ketNilai5, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(ketNilaiAkhir))
                .addGap(63, 63, 63))
            .addGroup(NPMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        NPMLayout.setVerticalGroup(
            NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NPMLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilai1)
                    .addComponent(npm)
                    .addComponent(ketNPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketNilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ketNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nama))
                    .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ketNilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nilai2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ketAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Alamat))
                    .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ketNilai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nilai3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NPMLayout.createSequentialGroup()
                        .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ketNilai4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nilai4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ketNilai5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nilai5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nilaiAkhir)
                            .addComponent(ketNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NPMLayout.createSequentialGroup()
                        .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ketMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Matakuliah))
                        .addGap(18, 18, 18)
                        .addGroup(NPMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanData)
                            .addComponent(hapusData))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>                        

    private void simpanDataActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        String npm = ketNPM.getText();
        String nama = ketNama.getText();
        String alamat = ketAlamat.getText();
        String matakuliah = ketMatakuliah.getText();
        
        double nilai1 = Double.parseDouble(ketNilai1.getText());
        double nilai2 = Double.parseDouble(ketNilai2.getText());
        double nilai3 = Double.parseDouble(ketNilai3.getText());
        double nilai4 = Double.parseDouble(ketNilai4.getText());
        double nilai5 = Double.parseDouble(ketNilai5.getText());
        
        double nilaiAkhir = (nilai1 * 0.1) + (nilai2 * 0.15) + (nilai3 * 0.25) + (nilai4 * 0.15) + (nilai5 * 0.35);
        
        ketNilaiAkhir.setText(String.valueOf(nilaiAkhir));
        
        model.addRow(new Object[]{npm, nama, alamat, matakuliah, nilaiAkhir});
        
        ketNPM.setText("");
        ketNama.setText("");
        ketAlamat.setText("");
        ketMatakuliah.setText("");
        ketNilai1.setText("");
        ketNilai2.setText("");
        ketNilai3.setText("");
        ketNilai4.setText("");
        ketNilai5.setText("");
        ketNilaiAkhir.setText("");
    }                                          

    private void ketNPMActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        ketNPM.setText("");
    }                                      

    private void ketNamaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        ketNama.setText("");
    }                                       

    private void ketAlamatActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        ketAlamat.setText("");
    }                                         

    private void ketMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        ketMatakuliah.setText("");
    }                                             

    private void ketNilai1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        ketNilai1.setText("");
    }                                         

    private void ketNilai2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        ketNilai2.setText("");
    }                                         

    private void ketNilai3ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        ketNilai3.setText("");
    }                                         

    private void ketNilai4ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        ketNilai4.setText("");
    }                                         

    private void ketNilai5ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        ketNilai5.setText("");
    }                                         

    private void ketNilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        nilaiAkhir = (nilai1 * 0.1) + (nilai2 * 0.15) + (nilai3 * 0.25) + (nilai4 * 0.15) + (nilai5 * 0.35);
    }                                             

    private void hapusDataActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            model.removeRow(selectedRow);
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdentitasMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdentitasMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdentitasMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdentitasMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IdentitasMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Matakuliah;
    private javax.swing.JPanel NPM;
    private javax.swing.JLabel Nama;
    private javax.swing.JButton hapusData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ketAlamat;
    private javax.swing.JTextField ketMatakuliah;
    private javax.swing.JTextField ketNPM;
    private javax.swing.JTextField ketNama;
    private javax.swing.JTextField ketNilai1;
    private javax.swing.JTextField ketNilai2;
    private javax.swing.JTextField ketNilai3;
    private javax.swing.JTextField ketNilai4;
    private javax.swing.JTextField ketNilai5;
    private javax.swing.JTextField ketNilaiAkhir;
    private javax.swing.JLabel nilai1;
    private javax.swing.JLabel nilai2;
    private javax.swing.JLabel nilai3;
    private javax.swing.JLabel nilai4;
    private javax.swing.JLabel nilai5;
    private javax.swing.JLabel nilaiAkhir;
    private javax.swing.JLabel npm;
    private javax.swing.JButton simpanData;
    // End of variables declaration                   
}
